# Generated by Django 5.2.6 on 2025-09-18 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_status', '0002_alter_serverstatus_vip_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverstatus',
            name='vip_mode',
            field=models.BooleanField(default=False),
        ),
    ]
