# Generated by Django 5.2.6 on 2025-09-18 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_corporation_id', models.BigIntegerField()),
                ('creator_id', models.BigIntegerField()),
                ('date_founded', models.DateTimeField()),
                ('executor_corporation_id', models.BigIntegerField(null=True)),
                ('faction_id', models.BigIntegerField(help_text='The faction the alliance is aligned with if enrolled in faction warfare.', null=True)),
                ('name', models.CharField(max_length=100)),
                ('ticker', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='AllianceIcon',
            fields=[
                ('alliance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='alliance.alliance')),
                ('px64x64', models.URLField()),
                ('px128x128', models.URLField()),
            ],
        ),
    ]
